### ISSUE TITLE
No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by MistaPidaus** [maartenvanvliet/serverless_ruby_image_resizer#1]
Hi. I cloned the repo and deploy to AWS Lambda. I test upload an image on the source s3 bucket, lambda triggered and keep getting this error:

```
Error raised from handler method
{
  "errorMessage": "No such file or directory @ rb_sysopen - /tmp/uploads/album/1/223b836359d0c6f1dcd85c167fd
2a19a",
  "errorType": "Function<Errno::ENOENT>",
  "stackTrace": [
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/plugins/response_target.rb:58:in `initialize'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/plugins/response_target.rb:58:in `new'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/plugins/response_target.rb:58:in `io'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/plugins/response_target.rb:31:in `block in add_e
vent_listeners'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/http/response.rb:171:in `block in listener'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/http/response.rb:180:in `block in emit'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/http/response.rb:180:in `each'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/http/response.rb:180:in `emit'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/http/response.rb:61:in `signal_headers'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/net_http/handler.rb:80:in `block (2 levels) in t

ransmit'",
    "/var/lang/lib/ruby/2.5.0/net/http.rb:1506:in `block in transport_request'",
    "/var/lang/lib/ruby/2.5.0/net/http/response.rb:165:in `reading_body'",
    "/var/lang/lib/ruby/2.5.0/net/http.rb:1505:in `transport_request'",
    "/var/lang/lib/ruby/2.5.0/net/http.rb:1467:in `request'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/net_http/connection_pool.rb:342:in `request'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/net_http/handler.rb:74:in `block in transmit'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/net_http/handler.rb:126:in `block in session'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/net_http/connection_pool.rb:100:in `session_for'
",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/net_http/handler.rb:121:in `session'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/net_http/handler.rb:73:in `transmit'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/net_http/handler.rb:47:in `call'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/seahorse/client/plugins/content_length.rb:17:in `call'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.52.0/lib/aws-sdk-s3/plugins/s3_signer.rb:109:in `call'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.52.0/lib/aws-sdk-s3/plugins/s3_signer.rb:57:in `call'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.52.0/lib/aws-sdk-s3/plugins/s3_host_id.rb:15:in `call'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.72.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'"
]
}
```

I'm not sure whats the problem.

Thanks!

**Comment by maartenvanvliet** [comment]
Did you find a solution? If so what was it?
